### ISSUE TITLE
No content to map due to end-of-input

### ISSUE THREAD

**Issue by gleporeNARA** [tballison/tika-gui-v2#120]
Getting a handful of errors as below:

WARN  [pool-5-thread-1] 10:09:48,594 org.tallison.tika.app.fx.batch.BatchProcess couldn't read status file
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4821) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at org.tallison.tika.app.fx.batch.BatchProcess.checkAsyncStatus(BatchProcess.java:145) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at org.tallison.tika.app.fx.status.StatusUpdater.call(StatusUpdater.java:56) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at org.tallison.tika.app.fx.status.StatusUpdater.call(StatusUpdater.java:35) ~[tika-gui-app.jar:1.0.0-ALPHA4]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by tballison** [comment]
I bumped this down to debug in the development branch.  I've since bumped it down to trace.  This kind of issue is expected, and the user should not know about it. 

Thank you for opening this issue!
